### ISSUE TITLE
Set up CI server

### ISSUE THREAD

**Issue by javidy** [SabuhiYusif/Tasker#5]
Shortlist CI tools 
Set up application to use CI builds

**Comment by javidy** [comment]
@SabuhiYusif  please provide you feedback on build steps that I thought of. Basically, I thinking to execute these steps in given order in travis.
1. gradle build  ( make sure to run on the same version of jdk as in app's docker image)
2. spin up postgress
3. wait for postgress to become available
4. spin up app container
5. run tests (this would probably be api endpoint tests)

**Comment by SabuhiYusif** [comment]
> @SabuhiYusif please provide you feedback on build steps that I thought of. Basically, I thinking to execute these steps in given order in travis.
> 
> 1. gradle build  ( make sure to run on the same version of jdk as in app's docker image)
> 2. spin up postgress
> 3. wait for postgress to become available
> 4. spin up app container
> 5. run tests (this would probably be api endpoint tests)

Yes basically what we need
